[project]
name = "dayuanlib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.15"
dependencies = [
    "numpy>=1.24.4",
    "scipy>=1.10.1",
]
